from ChatBotWeb.databaseconnection import connection

df = connection.mysql_query('''SELECT VE.MODELO AS MODELO, VEP.TIPO_PROBLEMA AS PROBLEMA, CLI.NOME_CLIENTE AS 
CLIENTE, VEP.KM_RODADO AS KM FROM VEICULO VE JOIN VEICULO_PROBLEMA VEP ON VE.ID_VEICULO = VEP.ID_VEICULO JOIN CLIENTE 
CLI ON CLI.ID_CLIENTE = VE.ID_VEICULO''')

