-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-08-25 11:29:47 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cliente (
    id_cliente   INTEGER NOT NULL,
    nome_cliente VARCHAR2(100) NOT NULL
);

ALTER TABLE cliente ADD CONSTRAINT cliente_pk PRIMARY KEY ( id_cliente );

CREATE TABLE funcionario (
    id_funcionario INTEGER NOT NULL,
    nome           VARCHAR2(100) NOT NULL,
    cargo          VARCHAR2
--  ERROR: VARCHAR2 size not specified
     NOT NULL,
    salario        FLOAT NOT NULL
);

ALTER TABLE funcionario ADD CONSTRAINT funcionario_pk PRIMARY KEY ( id_funcionario );

CREATE TABLE transacao (
    id_transacao               INTEGER NOT NULL,
    funcionario_id_funcionario INTEGER NOT NULL,
    vendas_id_venda            INTEGER NOT NULL,
    cliente_id_cliente         INTEGER NOT NULL
);

ALTER TABLE transacao ADD CONSTRAINT transacao_pk PRIMARY KEY ( id_transacao );

CREATE TABLE veiculos (
    id_veiculo INTEGER NOT NULL,
    modelo     VARCHAR2(100) NOT NULL,
    marca      VARCHAR2(100) NOT NULL,
    estoque    INTEGER NOT NULL
);

ALTER TABLE veiculos ADD CONSTRAINT veiculos_pk PRIMARY KEY ( id_veiculo );

CREATE TABLE vendas (
    id_venda            INTEGER NOT NULL,
    data_venda          DATE NOT NULL,
    veiculo_vendido     INTEGER NOT NULL,
    valor_venda         FLOAT NOT NULL,
    cliente_associado   INTEGER NOT NULL,
    veiculos_id_veiculo INTEGER NOT NULL
);

ALTER TABLE vendas ADD CONSTRAINT vendas_pk PRIMARY KEY ( id_venda );

ALTER TABLE transacao
    ADD CONSTRAINT transacao_cliente_fk FOREIGN KEY ( cliente_id_cliente )
        REFERENCES cliente ( id_cliente );

ALTER TABLE transacao
    ADD CONSTRAINT transacao_funcionario_fk FOREIGN KEY ( funcionario_id_funcionario )
        REFERENCES funcionario ( id_funcionario );

ALTER TABLE transacao
    ADD CONSTRAINT transacao_vendas_fk FOREIGN KEY ( vendas_id_venda )
        REFERENCES vendas ( id_venda );

ALTER TABLE vendas
    ADD CONSTRAINT vendas_veiculos_fk FOREIGN KEY ( veiculos_id_veiculo )
        REFERENCES veiculos ( id_veiculo );



-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   1
-- WARNINGS                                 0
